export type { BetterAuthInstance, AuthMailDispatcher } from './lib/better-auth.config';
export type { AuthenticatedSession } from './lib/better-auth.types';
export { BETTER_AUTH_INSTANCE } from './lib/better-auth-instance.token';
export { BetterAuthModule } from './lib/better-auth.module';
export type { AuthSessionPolicy } from './lib/auth-session-policy';
export { BetterAuthGuard } from './lib/better-auth.guard';
export { RolesGuard } from './lib/roles.guard';
export { Roles } from './lib/roles.decorator';
export { Public, IS_PUBLIC_KEY } from './lib/public.decorator';
export { CurrentUser } from './lib/current-user.decorator';
export { requireOrganizationId } from './lib/require-organization';
export { sessionCookieName } from './lib/session-cookie';
export { ApiKeyGuard } from './lib/api-key.guard';
export { AllowApiKey } from './lib/allow-api-key.decorator';
export type { AuthenticatedApiKey } from './lib/api-key.types';
export { CurrentApiKey } from './lib/current-api-key.decorator';
export { resolveOrganizationId } from './lib/resolve-organization';
export { requestOf, isPublic } from './lib/request-context';
