import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

// RFC 9457 problem details with extensions: code (snake_case i18n key), requestId, timestamp.
export class ProblemDetailsDto {
  @ApiProperty({
    description:
      'A URI reference identifying the problem type. SHOULD resolve to human-readable docs.',
    example: '/errors/not-found',
    // uri-reference (not uri): the value is relative when ERROR_DOCS_BASE_URL is unset, matching
    // `instance`. A strict validator rejects a relative value declared as an absolute `uri`.
    format: 'uri-reference',
  })
  type!: string;

  @ApiProperty({
    description: 'Short, human-readable summary of the problem type.',
    example: 'Not Found',
  })
  title!: string;

  @ApiProperty({
    description: 'HTTP status code generated by the origin server.',
    example: 404,
    minimum: 100,
    maximum: 599,
  })
  status!: number;

  @ApiPropertyOptional({
    description: 'Human-readable explanation specific to this occurrence.',
    example: 'The requested resource does not exist.',
  })
  detail?: string;

  @ApiPropertyOptional({
    description: 'URI reference identifying the specific occurrence (typically the request path).',
    // Neutral placeholder — at runtime this is the actual request path; a real route here would
    // misread as the failing endpoint under unrelated operations.
    example: '/api/v1/resource',
    format: 'uri-reference',
  })
  instance?: string;

  @ApiProperty({
    description:
      'Stable, machine-readable error code (snake_case). Use this for client-side i18n keys and logic switching — message text may change without notice.',
    // Kept in sync with the `type`/`title`/`status` example above so the schema view renders one
    // coherent 404 example (not a mix of 404 + route_not_found + 503 checks).
    example: 'not_found',
  })
  code!: string;

  @ApiPropertyOptional({
    description:
      'Request correlation ID. Mirrors the `X-Request-Id` response header (the trace id when tracing is active).',
    example: '4bf92f3577b34da6a3ce929d0e0e4736',
  })
  requestId?: string;

  @ApiProperty({
    description: 'ISO 8601 UTC timestamp when the error was produced.',
    example: '2026-04-30T22:28:27.356Z',
    format: 'date-time',
  })
  timestamp!: string;

  @ApiPropertyOptional({
    description:
      'Present only on a health-probe 503: the dependencies that reported `down`, so an operator can see which one failed without reading logs.',
    type: 'object',
    additionalProperties: {
      type: 'object',
      properties: {
        status: { type: 'string', example: 'down' },
        message: { type: 'string' },
      },
      required: ['status'],
    },
    example: { redis_cache: { status: 'down', message: 'redis_cache check failed' } },
  })
  checks?: Record<string, { status: string; message?: string }>;
}

export class ValidationErrorItemDto {
  @ApiProperty({
    description: 'Path to the offending field. Dotted notation for objects, bracket for arrays.',
    example: 'items[0].quantity',
  })
  path!: string;

  @ApiProperty({
    description: 'Stable error code for this specific violation (snake_case).',
    example: 'out_of_range',
  })
  code!: string;

  @ApiProperty({
    description:
      'Human-readable message translated to the resolved locale (Accept-Language / ?lang / x-lang header). Falls back to English when the requested locale is unavailable.',
    example: 'Must be at least 1.',
  })
  message!: string;

  @ApiPropertyOptional({
    description:
      'Stable i18n key the server used to produce `message`. Echo it instead of the localized text when persisting violations for later replay.',
    example: 'validation.out_of_range',
  })
  messageKey?: string;

  @ApiPropertyOptional({
    description: 'Underlying validator name (e.g. `min`, `isEmail`, `maxLength`).',
    example: 'min',
  })
  rule?: string;

  @ApiPropertyOptional({
    description: 'Validator constraint parameters (e.g. `{ min: 1 }`, `{ max: 100 }`).',
    type: 'object',
    additionalProperties: true,
    example: { min: 1 },
  })
  constraint?: Record<string, unknown>;

  @ApiPropertyOptional({
    description:
      'Value received from the client that failed validation. Free-form: mirrors the offending input, which may be any JSON type (string, number, boolean, object or array). Sensitive fields are redacted.',
    // `received` is genuinely polymorphic (class-validator's raw `err.value`). Declaring `oneOf`
    // makes @nestjs/swagger drop the reflected `type: 'object'`, so orval emits a truthful union
    // instead of mis-typing every offending value as an object map. The object branch is `nullable`
    // because a field failing @IsNotEmpty can carry a `null` value — OpenAPI 3.0 admits null only via
    // a per-branch `nullable`, not a top-level one.
    oneOf: [
      { type: 'string' },
      { type: 'number' },
      { type: 'boolean' },
      { type: 'object', nullable: true },
      { type: 'array', items: {} },
    ],
    example: 0,
  })
  received?: unknown;
}

export class ValidationProblemDetailsDto extends ProblemDetailsDto {
  @ApiProperty({
    description: 'Per-field violations. Frontend should highlight each `path` independently.',
    type: [ValidationErrorItemDto],
  })
  errors!: ValidationErrorItemDto[];
}
