import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

/**
 * RFC 9457 Problem Details for HTTP APIs (https://www.rfc-editor.org/rfc/rfc9457).
 *
 * Wire `Content-Type: application/problem+json`. Field set follows the RFC core
 * (`type`, `title`, `status`, `detail`, `instance`) plus the extensions
 * `code`, `requestId`, `timestamp` adopted by Linear / Vercel / modern Stripe.
 *
 * Naming rationale:
 *  - JSON keys are camelCase to match the rest of the codebase.
 *  - The `code` STRING value is snake_case so it stands out from object keys
 *    and so frontends can use it as a stable i18n key.
 *  - The `instance` URI is the request path for log-grepping.
 */
export class ProblemDetailsDto {
  @ApiProperty({
    description:
      'A URI reference identifying the problem type. SHOULD resolve to human-readable docs.',
    example: '/errors/not-found',
    format: 'uri',
  })
  type!: string;

  @ApiProperty({
    description: 'Short, human-readable summary of the problem type.',
    example: 'Not Found',
  })
  title!: string;

  @ApiProperty({
    description: 'HTTP status code generated by the origin server.',
    example: 404,
    minimum: 100,
    maximum: 599,
  })
  status!: number;

  @ApiPropertyOptional({
    description: 'Human-readable explanation specific to this occurrence.',
    example: 'Cannot GET /admin/queues',
  })
  detail?: string;

  @ApiPropertyOptional({
    description: 'URI reference identifying the specific occurrence (typically the request path).',
    example: '/api/v1/admin/queues',
    format: 'uri-reference',
  })
  instance?: string;

  @ApiProperty({
    description:
      'Stable, machine-readable error code (snake_case). Use this for client-side i18n keys and logic switching — message text may change without notice.',
    example: 'route_not_found',
  })
  code!: string;

  @ApiPropertyOptional({
    description: 'Request correlation ID. Mirrors the `X-Request-Id` response header.',
    example: 'req-01HXY7K3MN8P2RZ4QW9TB6FH3D',
  })
  requestId?: string;

  @ApiProperty({
    description: 'ISO 8601 UTC timestamp when the error was produced.',
    example: '2026-04-30T22:28:27.356Z',
    format: 'date-time',
  })
  timestamp!: string;
}

export class ValidationErrorItemDto {
  @ApiProperty({
    description:
      'Path to the offending field. Dotted notation for objects, bracket for arrays. Prefixed with `query.`/`header.`/`path.` when the violation is not in the request body.',
    example: 'items[0].quantity',
  })
  path!: string;

  @ApiProperty({
    description: 'Stable error code for this specific violation (snake_case).',
    example: 'out_of_range',
  })
  code!: string;

  @ApiProperty({
    description: 'Default human-readable message (English). Use `code` for i18n keys.',
    example: 'Must be at least 1.',
  })
  message!: string;

  @ApiPropertyOptional({
    description: 'Underlying validator name (e.g. `min`, `isEmail`, `maxLength`).',
    example: 'min',
  })
  rule?: string;

  @ApiPropertyOptional({
    description: 'Validator constraint parameters (e.g. `{ min: 1 }`, `{ max: 100 }`).',
    type: 'object',
    additionalProperties: true,
    example: { min: 1 },
  })
  constraint?: Record<string, unknown>;

  @ApiPropertyOptional({
    description: 'Value received from the client. Sensitive fields are redacted.',
    example: 0,
  })
  received?: unknown;
}

export class ValidationProblemDetailsDto extends ProblemDetailsDto {
  @ApiProperty({
    description: 'Per-field violations. Frontend should highlight each `path` independently.',
    type: [ValidationErrorItemDto],
  })
  errors!: ValidationErrorItemDto[];
}
