services:
  postgres:
    environment:
      POSTGRES_DB: nestjs_test_db
    ports:
      - '5433:5432'
    tmpfs:
      - /var/lib/postgresql

  redis-cache:
    ports:
      - '6381:6379'

  redis-queue:
    ports:
      - '6382:6380'
