services:
  postgres:
    environment:
      POSTGRES_DB: nestjs_test_db
    ports:
      - '127.0.0.1:5433:5432'
    tmpfs:
      - /var/lib/postgresql

  redis-cache:
    ports:
      - '127.0.0.1:6381:6379'

  redis-queue:
    ports:
      - '127.0.0.1:6382:6380'
