-- Backoff-aware claim path for the outbox relay. The existing
-- (processedAt, createdAt) index cannot serve the added `nextAttemptAt <= NOW()` predicate.
--
-- CONCURRENTLY, and alone in its own migration, because `outbox_events` is the most
-- write-hot table in the schema: OutboxPublisher inserts into it from inside a request's
-- interactive transaction, and the relay updates it every poll tick. A plain CREATE INDEX
-- takes a SHARE lock that blocks those writes for the whole build — and the documented
-- rollout (docs/deployment.md) runs the migration image against the live database *before*
-- restarting the services, so producers are still writing at that moment. On a grown table
-- that stall propagates into open user transactions.
--
-- Prisma does not wrap migration files in a transaction, so CONCURRENTLY is safe to use
-- here; it is split into its own migration anyway so the instant, unfailable column change
-- can never be rolled back by an index build that failed.
--
-- OPERATIONAL NOTE: a failed CONCURRENTLY build leaves an INVALID index behind and marks
-- this migration failed. Recover with:
--     DROP INDEX IF EXISTS "outbox_events_processedAt_nextAttemptAt_createdAt_idx";
--     npx prisma migrate resolve --rolled-back 20260726000100_outbox_retry_backoff_index
-- then re-run `prisma migrate deploy`. Do NOT add IF NOT EXISTS to the statement below: it
-- would match the leftover INVALID index by name and silently skip the rebuild, leaving the
-- claim query without a usable index forever.
CREATE INDEX CONCURRENTLY "outbox_events_processedAt_nextAttemptAt_createdAt_idx"
    ON "outbox_events"("processedAt", "nextAttemptAt", "createdAt");
